### PR TITLE
Update Route.php

### PR DESCRIPTION
**Pull request by joanhey**
Fix:
TypeError(0):str_replace(): Argument #3 ($subject) must be of type array|string, null given
/duckphp/vendor/dvaknheo/duckphp/src/Core/Route.php : 274

### CODE REVIEW

**Comment by dvaknheo** [comment]
In v1.2.10 stable version , I change  resolve by judge type， 
        $base_class = str_replace('~', $this->namespace_prefix, $this->options['controller_base_class'] ?? '');
at now ,when i found this pr , ok , you are the better way .
I may thinked  developer can take not only string , to is_subclass_of() at i first write that code

**Comment by joanhey** [comment]
I found the problem in the techempower benchmark.

I updated the bench with v1.2.10 and PHP8:
https://github.com/TechEmpower/FrameworkBenchmarks/pull/6311

And changed to a faster array_combine in the fortunes test.
https://github.com/TechEmpower/FrameworkBenchmarks/pull/6311/commits/ef8653913b19485fc72d51bd209282f43210ab10

Now it's faster, later I will add the JIT.

**Comment by joanhey** [comment]
With PHP7.4 and v1.2.8:
https://www.techempower.com/benchmarks/#section=test&runid=646af5ea-0fae-448d-b77d-bc27b13d73e5&hw=ph&test=composite&a=2&f=zik0zj-zik0zj-zik0zj-zik0zj-zik0zj-zik0zj-zik0zj-zik0zj-zik0zj-zik0zj-zijxtr-sf

With PHP8.0 and v1.2.10:
https://www.techempower.com/benchmarks/#section=test&runid=f8a61dd3-ead6-4979-b375-b44873987350&hw=ph&test=composite&a=2&f=zik0zj-zik0zj-zik0zj-zik0zj-zik0zj-zik0zj-zik0zj-zik0zj-zik0zj-zik0zj-zijxtr-sf

Without JIT enabled.

**Comment by dvaknheo** [comment]
> I found the problem in the techempower benchmark.
> 
> I updated the bench with v1.2.10 and PHP8:
> [TechEmpower/FrameworkBenchmarks#6311](https://github.com/TechEmpower/FrameworkBenchmarks/pull/6311)
> 
> And changed to a faster array_combine in the fortunes test.
> [TechEmpower/FrameworkBenchmarks@ef86539](https://github.com/TechEmpower/FrameworkBenchmarks/commit/ef8653913b19485fc72d51bd209282f43210ab10)
> 
> Now it's faster, later I will add the JIT.

thank you  very much . It's grad , I am planning to review the code today and tomorrow.

**Pull request merged**
